# -*- coding: utf-8 -*-

{
    'name': 'Prakruti Product Pvt Ltd',
    'version': '1.0.0',
    'category': 'Prakruti Product Pvt Ltd',
    "sequence": 1,
    'summary': 'Prakruti Product Pvt Ltd',
    'complexity': "Medium",
    'description': """
        This module provide overall Prakruti Product Pvt Ltd Maintainance
        Features includes managing
            * Contact 
            * Item
            * Item Specification
            * Purchase
            * Stores(Stock)
            * Logistics
            * Manufacturing """,
    'author': 'NetSoft Group',
    'website': 'http://www.netsoftgroup.in/',
    'depends': ['base','web','product','stock','purchase','mail','account','email_template'],
    
	'data': [
            'wizard/batch_wizard_view.xml',
            'wizard/prakruti_grn_store_issue_wizard.xml',
            'wizard/prakruti_production_transfer_note_wizard.xml', 
            'wizard/prakruti_bill_of_material_wizard.xml', 
            'wizard/prakruti_syrup_wizard.xml', 
            'wizard/prakruti_syrup_packing_wizard.xml',  
            'wizard/prakruti_tablet_wizard.xml', 
            'wizard/prakruti_tablet_packing_wizard.xml', 
            'wizard/prakruti_formulation_packing_wizard.xml', 
            'wizard/prakruti_formulation_wizard.xml', 
            
            'security/prakruti_security.xml',
            'security/ir.model.access.csv',
            'security/prakruti_multi_company_security.xml', 
            
            'views/res_partner_view.xml',
            'views/product_template_view.xml',
            'views/product_specification_view.xml',
            'views/workflow.xml',
            'views/purchase_requisition_view.xml',
            'views/purchase_requisition_approve_view.xml',         
            'views/price_request_view.xml',
            'views/purchase_order_quotation_view.xml',
            'views/purchase_order_quotation_anaysis_view.xml',
            'views/purchase_order.xml',
            'views/purchase_invoice_view.xml',
            'views/purchase_return_view.xml',
            'views/purchase_requistion_analysis_view.xml', 
            'views/grn_analysis.xml',
            'views/grn_inspection_details.xml',
            'views/material_rejection_note_view.xml', 
            'views/prakruti_stock_adjustments.xml',
            'views/specification_ar_no.xml',     
            
            'account/prakruti_credit_note.xml',
            'account/prakruti_debit_note.xml',
            'account/prakruti_debit_note_ha.xml',  
            
            'quality_control/prakruti_quality_control.xml',
            'quality_control/prakruti_quality_control_ha.xml',
            
            'stores/prakruti_store_request_view.xml',
            'stores/prakruti_store_approve_request_view.xml',
            'stores/prakruti_store_issue_view.xml',
            'stores/prakruti_dispatch.xml',
            'stores/prakruti_dispatch_qc.xml',
            'stores/prakruti_dispatch_qc_ha.xml', 
            'stores/prakruti_process_dispatch_qa.xml',
            'stores/prakruti_process_dispatch_qa_ha.xml',
            
            'logistics/prakruti_logistics_po_tracking.xml',
            'logistics/prakruti_logistics_invoice_tracking.xml',
            
            'sales/prakruti_sales_inquiry.xml',
            'sales/prakruti_sales_invoice.xml',
            'sales/prakruti_sales_order.xml',
            'sales/prakruti_sales_proforma_invoice.xml',
            'sales/prakruti_sales_quotation.xml',
            'sales/prakruti_sales_return.xml',
            'sales/prakruti_gate_pass.xml',
            'sales/prakruti_gate_pass_manual.xml', 
                      
            'production/prakruti_production_slip.xml',        
            'production/prakruti_bmr_requisition.xml',        
            'production/prakruti_production_planning.xml',
            
            'sales_grn/sales_return_grn.xml',
            'sales_grn/sales_return_grn_qc.xml',
            'sales_grn/sales_return_grn_qc_ha.xml',            
            'sales_grn/sales_scrap.xml',
            'rejection_store/prakruti_material_rejected_store.xml',
            
            'report/meterial_requistion_issue.xml',
            'report/report_grn.xml', 
            'report/report_material_rejection_note.xml',
            'report/report_salesinquiry.xml',
            'report/report_specification.xml',         
            'report/report_purchase_requistion.xml',
            'report/purchase_report.xml',           
            'report/report_gatepass.xml',           
            'report/report_prakruti_storerequest.xml',
            'report/report_manual_gatepass.xml',
            'report/report_finished_product_specification.xml',
            'report/report_prakruti_all_products_list.xml',
            'report/report_sales_production_slip.xml',
            
            #PRODUCTION           
            'production_security/prakruti_security.xml',
            'production_security/ir.model.access.csv',
            'production_corporate/prakruti_main_plant.xml',
            'production_corporate/prakruti_sub_plant.xml',
            'production_corporate/prakruti_shift_master.xml',
            'production_corporate/prakruti_breakdown_item.xml',
            'production_corporate/prakruti_sieve_master.xml',
            'production_corporate/prakruti_mesh_master.xml',
            'production_corporate/prakruti_batch_master.xml',
            'production_corporate/prakruti_extraction_changes.xml',
            'production_corporate/prakruti_manage_parameters.xml',
            'production_corporate/prakruti_stage.xml', 
            'production_corporate/prakruti_process_order.xml',
            'production_corporate/prakruti_machine.xml',
            #'production_corporate/prakruti_shift_assignment.xml',
            'production_production/prakruti_bill_of_material.xml',
            'production_production/prakruti_production_view.xml',
            'production_production/prakruti_syrup.xml',
            'production_production/prakruti_tablet.xml', 
            'production_production/prakruti_syrup_production.xml', 
            'production_production/prakruti_tablet_production.xml', 
            'production_production/prakruti_standard_product.xml',            
            'production_production/prakruti_production_transfer_note_qc.xml',
            'production_production/prakruti_production_inward.xml',
            'production_production/prakruti_production_transfer_note_ha.xml',  
            'production_production/prakruti_production_transfer_note.xml', 
            'production_production/prakruti_destruction_note.xml',  
            'production_production/prakruti_powder_production.xml', 
            'production_production/prakruti_powder.xml',  
            
            #Added by Karan for Production BMR on 20170911             
            'production_report/report_production_transfer_note.xml',
            'production_report/production_report.xml',      
            'production_report/report_bmr_syrup_production.xml',         
            'production_report/report_bmr_extraction_production.xml',         
            'production_report/report_bmr_tablet_production.xml',
            
            
            #Email
            #'email/prakruti_template_creation_data.xml',
            #'email/prakruti_purchase_invoice.xml',
            #'email/prakruti_purchase_order.xml',
            #'email/prakruti_grn_inspection_details.xml',
            #'email/prakruti_purchase_quality_control.xml',
            #'email/prakruti_gate_pass.xml',
            #'email/prakruti_store_issue.xml',
            #'email/prakruti_sales_order.xml',
            #'email/prakruti_production_slip.xml',
            #'email/prakruti_sales_inquiry.xml',
            #'email/prakruti_store_request.xml',
            #'email/prakruti_store_approve_request.xml',
            #'email/prakruti_requisition.xml',
            #'email/prakruti_bill_of_material.xml',
            #'email/prakruti_tablet.xml',
            #'email/prakruti_syrup.xml',
            #'email/prakruti_purchase_requisition_approve.xml',
            #'email/prakruti_purchase_requistion_analysis.xml',
            #'email/prakruti_credit_note.xml',
            #'email/prakruti_sales_quotation.xml',
            #'email/prakruti_logistics_po_tracking.xml',
            #'email/prakruti_logistics_invoice_tracking.xml',
            
            #EMAIL NOTIFICATIONS
            #'email_notifications/prakruti_production_planning_notifications.xml',
            #'email_notifications/prakruti_production_planning_notifications_template.xml',
            'email_notifications/prakruti_purchase_requisition_notifications.xml',
            'email_notifications/prakruti_purchase_requisition_notifications_template.xml',
            'email_notifications/prakruti_purchase_requisition_approve_notifications.xml',
            'email_notifications/prakruti_purchase_requisition_approve_notifications_template.xml',
            'email_notifications/prakruti_purchase_requistion_analysis_notifications.xml',
            'email_notifications/prakruti_purchase_requistion_analysis_notifications_template.xml',
            'email_notifications/prakruti_price_request_notifications.xml',
            'email_notifications/prakruti_price_request_notifications_template.xml',
            'email_notifications/prakruti_purchase_order_quotation_notifications.xml',
            'email_notifications/prakruti_purchase_order_quotation_notifications_template.xml',
            'email_notifications/purchase_order_quotation_analysis_notifications.xml',
            'email_notifications/purchase_order_quotation_analysis_notifications_template.xml',
            'email_notifications/purchase_order_notifications.xml',
            'email_notifications/purchase_order_notifications_template.xml',
            'email_notifications/prakruti_grn_analysis_notifications.xml',
            'email_notifications/prakruti_grn_analysis_notifications_template.xml',
            'email_notifications/prakruti_grn_inspection_details_notifications.xml',
            'email_notifications/prakruti_grn_inspection_details_notifications_template.xml',
            'email_notifications/prakruti_quality_control_notifications.xml',
            'email_notifications/prakruti_quality_control_notifications_template.xml',
            'email_notifications/prakruti_quality_control_ha_notifications_template.xml',
            'email_notifications/prakruti_quality_control_ha_notifications.xml',
            'email_notifications/prakruti_store_approve_request_notifications.xml',
            'email_notifications/prakruti_store_approve_request_notifications_template.xml',
            'email_notifications/prakruti_store_issue_notifications.xml',
            'email_notifications/prakruti_store_issue_notifications_template.xml',
            'email_notifications/prakruti_po_tracking_notifications.xml',
            'email_notifications/prakruti_po_tracking_notifications_template.xml',
            'email_notifications/prakruti_invoice_tracking_notifications.xml',
            'email_notifications/prakruti_invoice_tracking_notifications_template.xml',
            'email_notifications/prakruti_debit_note_ha_notifications_template.xml',
            'email_notifications/prakruti_debit_note_ha_notifications.xml',
            'email_notifications/prakruti_bill_of_material_notifications.xml',
            'email_notifications/prakruti_bill_of_material_notifications_template.xml',
            
            'email_notifications/prakruti_syrup_notifications.xml',
            'email_notifications/prakruti_syrup_notifications_template.xml',
            'email_notifications/prakruti_tablet_notifications.xml',
            'email_notifications/prakruti_tablet_notifications_template.xml',
            'email_notifications/prakruti_production_transfer_note_qc_notifications_template.xml',
            'email_notifications/prakruti_production_transfer_note_qc_notifications.xml',
            'email_notifications/prakruti_production_transfer_note_ha_notifications.xml',
            'email_notifications/prakruti_production_transfer_note_ha_notifications_template.xml',
            'email_notifications/prakruti_production_notifications.xml',
            'email_notifications/prakruti_production_notifications_template.xml',
            'email_notifications/prakruti_syrup_production_notifications.xml',
            'email_notifications/prakruti_syrup_production_notifications_template.xml',
            'email_notifications/prakruti_tablet_production_notifications.xml',
            'email_notifications/prakruti_tablet_production_notifications_template.xml',
            'email_notifications/prakruti_sales_quotation_notifications.xml',
            'email_notifications/prakruti_sales_quotation_notifications_template.xml',
            'email_notifications/prakruti_gate_pass_notifications.xml',
            'email_notifications/prakruti_gate_pass_notifications_template.xml',
            'email_notifications/prakruti_production_inward_notifications.xml',
            'email_notifications/prakruti_production_inward_notifications_template.xml',
            'email_notifications/prakruti_sales_order_notifications.xml',
            'email_notifications/prakruti_sales_order_notifications_template.xml',
            'email_notifications/prakruti_production_slip_notifications.xml',
            'email_notifications/prakruti_production_slip_notifications_template.xml',
            'email_notifications/prakruti_sales_invoice_notifications.xml',
            'email_notifications/prakruti_sales_invoice_notifications_template.xml',
            'email_notifications/prakruti_dispatch_notifications.xml',
            'email_notifications/prakruti_dispatch_notifications_template.xml',
            'email_notifications/prakruti_quality_check_notifications.xml',
            'email_notifications/prakruti_quality_check_notifications_template.xml',
            'email_notifications/prakruti_quality_check_ha_notifications.xml',
            'email_notifications/prakruti_quality_check_ha_notifications_template.xml',
            'email_notifications/prakruti_sales_return_grn_notifications.xml',
            'email_notifications/prakruti_sales_return_grn_notifications_template.xml',
            'email_notifications/prakruti_sales_return_grn_qc_notifications.xml',
            'email_notifications/prakruti_sales_return_grn_qc_notifications_template.xml',
            'email_notifications/prakruti_sales_return_grn_qc_ha_notifications.xml',
            'email_notifications/prakruti_sales_return_grn_qc_ha_notifications_template.xml',
            
            
            
            
            # GST format print out
            'gst/purchase_quotation_gst.xml',
            'gst/purchase_order_gst.xml',
            'gst/purchase_invoice_gst.xml',
            
            'gst/sales_quotation_gst.xml',
            'gst/sales_order_gst.xml',
            'gst/sales_proforma_invoice_gst.xml',
            'gst/sales_local_invoice_gst.xml',
            'gst/sales_export_invoice_gst.xml',
            
            #Stock table Added as on 20170925 by Karan
            'stores/prakruti_stock.xml',
            'stores/prakruti_material_outward_note_view.xml',
            #Reserved Table for Production 
            #Added by Karan on 30/11/2017
            'production/prakruti_reserved_product.xml',
            
            
            
            ],
        
    'js': [''],
    'css': [''],
    'application': True,
    'auto_install': True,
    'installable': True
}	
	
